name: AutoPy2Exe

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.1
    - name: upgrade pip
      run: |
        pip install --upgrade pip wheel setuptools
      shell: bash

    - name: install requirements
      run: |
        pip install -r requirements.txt

    - name: build
      run: |
        python -m pyinstaller --clean -y --dist ./dist/windows main.py

    - uses: actions/upload-artifact@v2
      with:
        name: my-app
        path: dist/windows
